### PR TITLE
Add missing SCI demos.

### PR DESCRIPTION
**Pull request by OmerMor**
Also, for demos that scummvm doesn't support well yet, I added them as xml comment, for easy addition once we have better support.

### CODE REVIEW

**Comment by sev-** [comment]
Those are hidden on purpose: they're not yet supported by ScummVM.

**Comment by OmerMor** [comment]
But some of them are fully playable, e.g. Quest for Glory 1 VGA, Hoyle3.

**Comment by OmerMor** [comment]
branch is synced.

**Comment by Kirben** [comment]
I added the working game demos (Hoyle Official Book of Games: Volume 3, King's Quest VI
Quest for Glory I, Quest for Glory IV) to the web site.

The Gabriel Knight demo might get broken, as support for full game is been worked on, as I noticed the non-interactive demo of The Lighthouse has been broken recently.

**Comment by OmerMor** [comment]
Then I guess this patch is no longer needed...

**Pull request closed without merging**
