### PR TITLE
WEB: List game titles for screenshots in alphabetical order

### PR DESCRIPTION
**Pull request by dafioram**
I used the convention that if a game title starts with a "The"
then the next word is used for determining order.

### CODE REVIEW

**Comment by lotharsm** [comment]
Thanks for your work!

Just my personal opinion, I would prefer to have a naming scheme like "Curse of Monkey Island, The" instead, have you considered that?

**Comment by criezy** [comment]
Thank you. Currently it looks like some games are in alphabetical order (for example the Revolution Software games and SCI games (almost - one game is misplaced) while SCUMM games for example appear to be sorted from older to newer. Some consistency would indeed be nice. 

Interestingly the Compatibility page is similarly inconsistently sorted and seems to be using mostly alphabetical order, but not for SCUMM games. Maybe that one should be changed as well?

Alphabetical order is fine for me. I think it makes it easier to find a game as I do now my alphabet while I don't know the release date of each game.

Also personally I don't like the naming scheme proposed by @lotharsm as it breaks the natural reading of a text and makes it harder to read.

**Comment by Mataniko** [comment]
We can also simply call `sort($games)` in https://github.com/scummvm/scummvm-web/blob/c4c59152150042ef450827d464df8c0b91d8617d/include/Models/ScreenshotsModel.php#L25 instead of manually sorting the XML every time which will be prone to errors.

I don't have a personal preference for games starting with "The" and how they're sorted, but we should be consistent.

**Comment by dafioram** [comment]
That works for me. Is it also possible to sort the game titles on the compatibility page also?

**Comment by Mataniko** [comment]
@dafioram Should work the same way, look in CompatibilityModel.php

**Comment by dafioram** [comment]
Having it automat

**Pull request closed without merging**
