### PR TITLE
DOC: Adding prerequisite to install PHP and PECL

### PR DESCRIPTION
**Pull request by Thunderforge**
Thanks to the help of @SupSuper, @lotharsm, and @criezy on Discord, I was able to figure out how to get past an issue I was having with YAML pages like `/credits` not showing up correctly. I've added instructions to README.md so that others can avoid the same issues.

Includes a description of why the Apple-supplied version of PHP won't work, which is an issue that I ran into.

### CODE REVIEW

**Comment by lotharsm** [comment]
Thanks a lot for your contribution! Could you alter the commit messages to match our guidelines? In this case, the commit messages should be somthing along the lines of

- DOC: Adding prerequisite to install PHP and PECL
- DOC: Adding link to PHP Homebrew instructions for macOS

**Comment by Thunderforge** [comment]
@lotharsm The commit messages have been reworded!

**Comment by SupSuper** [comment]
@Thunderforge Looks like you added a change from another PR in here (data/links.yml): https://github.com/scummvm/scummvm-web/pull/114/commits/6d89adca9d27f4ebce3828658735fb9c2a262408

**Comment by Thunderforge** [comment]
@SupSuper Thanks. Fixed it.

It looks like I'm getting `[list-item-indent] Incorrect list-item indent: add 2 spaces` after I changed my commits. No clue why it didn't apply the first time around, or why it wasn't a problem with the old code. I assume that it wants me to indent the whole list block with two spaces?

**Comment by Thunderforge** [comment]
Can I get some help with the code formatting on this? I indented everything in the list two spaces, and now the Codacy review says that I have simultaneously have the following:

* Fixed issue: line 16 `[list-item-indent] Incorrect list-item indent: add 2 spaces`
* New issue: line 16 `[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces`

So which does it want? Me to add two spaces or remove them?

**Comment by lotharsm** [comment]
IIRC, the correct syntax for nested lists like this is

```
* [PHP](https://www.php.net/manual/en/install.php)
  - After installing, run `pecl install yaml` to install the PHP YAML extension
  - ...```

**Comment by Thunderforge** [comment]
@lotharsm Hmm, it doesn't like using `-` for list items and says I should use `*` exclusively.

**Comment by lotharsm** [comment]
Thanks again for your contribution! Merging after checking out the Discord discussion.

**Comment by Thunderforge** [comment]
For reference, here's the Discord discussion being referenced:

> Thunderforge Yesterday at 7:16 PM
Can I get some help on this PR? Basically, Codacy complains that my markdown lists don't have two spaces, then when I add them, it says I should remove the two spaces I just added. :/ #114

> SupSuper Yesterday at 7:18 PM
@Thunderforge i would ignore it since it's flagging every scummvm markdown like that
as long as it displays properly in github, it's fine

> Thunderforge Yesterday at 7:44 PM
@SupSuper Thanks! I'll put it in a way that looks good on GitHub

**Pull request merged**
