### PR TITLE
IMAGES: Adding Lure of the Temptress (Italian) screenshots

### PR DESCRIPTION
**Pull request by SupSuper**
https://bugs.scummvm.org/ticket/12407

Lure of the Temptress (EGA/DOS/Italian)

### CODE REVIEW

**Review by Thunderforge — CHANGES_REQUESTED** [review]
[From the wiki](https://wiki.scummvm.org/index.php?title=Screenshots):

> For each game, we would like to have a small (say, between 2 and 5) number of screenshots which give users a good idea of what the game looks like to play.

This PR has too many screenshots. Can you cull it down to no more than 10?

**Comment by sev-** [comment]
The Wiki continues:

> If the game is available in different languages or versions, it would also be nice to have a screenshot or two showing the differences of those versions.

Please, cut it down to 2

**Comment by SupSuper** [comment]
Down to 2.

**Comment by SupSuper** [comment]
Down to 2.

**Review by Thunderforge — APPROVED** [review]

**Comment by Thunderforge** [comment]
Looks good, merging.

**Pull request merged**
