### PR TITLE
IMAGES: Adding Myst (Italian) screenshots

### PR DESCRIPTION
**Pull request by SupSuper**
https://bugs.scummvm.org/ticket/12406

Myst (Windows/Italian)

### CODE REVIEW

**Comment by Thunderforge** [comment]
Just to clarify: are these for the original  *Myst* and not *Myst: Masterpiece Edition* (or *Myst* 2021)?

**Comment by SupSuper** [comment]
From the description it should be the original version, and indeed the screenshots seem to still have the original 8-bit artifacting (that was fixed in the Masterpiece Edition).

**Comment by Thunderforge** [comment]
[From the wiki](https://wiki.scummvm.org/index.php?title=Screenshots):

> For each game, we would like to have a small (say, between 2 and 5) number of screenshots which give users a good idea of what the game looks like to play. 

This PR has 28 screenshots. I know you're not the original author, but can you cull it down to no more than 10?

**Review by Thunderforge — CHANGES_REQUESTED** [review]
Need to cull down to 10 or fewer images.

**Comment by sev-** [comment]
I would say: cut it down to 2, where Italian will be prominently seen.

Screenshots are rotated on the front page and this will dwarf other games

**Comment by Thunderforge** [comment]
Looks good, merging.

**Review by Thunderforge — APPROVED** [review]

**Pull request merged**
