### PR TITLE
IMAGES: Adding Blazing Dragons screenshots

### PR DESCRIPTION
**Pull request by SupSuper**
https://bugs.scummvm.org/ticket/12433

Blazing Dragons (Sony Playstation/English (US))

### CODE REVIEW

**Review by Thunderforge — CHANGES_REQUESTED** [review]
[From the wiki](https://wiki.scummvm.org/index.php?title=Screenshots):

> For each game, we would like to have a small (say, between 2 and 5) number of screenshots which give users a good idea of what the game looks like to play.

This PR has too many screenshots. Can you cull it down to no more than 10?

**Comment by sev-** [comment]
Not more than 5 per game, please. Wiki is clear here.

**Review by Thunderforge — APPROVED** [review]

**Comment by Thunderforge** [comment]
Looks great! I especially like how several of them have English text, clearly indicating that this is the English version.

**Comment by Thunderforge** [comment]
I didn't notice this until later, but the language in the filename was `us`. I had to change it to `en-us` instead ("United States" is not a valid language, but "English - United States" is).

**Pull request merged**
