### PR TITLE
WEB: Remove FAQ and Documentation pages

### PR DESCRIPTION
**Pull request by Mataniko**
This PR removes both the FAQ and Documentation pages, instead linking them to the new docs portal.

In the PR:

- Updated menu links
- Redirect /faq and /documentation to the respective pages
- Remove newly (and some older) unused translation keys from strings file
- Remove data, pages, object and model files related to docs and faq

### CODE REVIEW

**Review by lotharsm — APPROVED** [review]
Looks good to me, also very nice to see some of the old/obsolete/duplicated strings getting removed.

Do we already have a solution for handling translations for the FAQ or any plans to add them at a later point in time?

**Comment by Mataniko** [comment]
readthedocs supports localization, so in whatever manner works there.

The FAQ there isn't 1:1 to the one on the site, so copying over the translation didn't make sense

**Review by Thunderforge — APPROVED** [review]

**Comment by bluegr** [comment]
Some of the resources linked in the current documentation page are not available in the new documentation.

In particular:
- Documentation on wiki
- Game data files
- ScummVM current areas of focus
- Source code documentation 

Or at least I couldn't find them in docs.scummvm.org.
The FAQ and the README contents are OK.

As such, it would be necessary to add these sections to the docs before removing the legacy pages with this PR.

**Comment by Mataniko** [comment]
Thanks @bluegr - It's fair to point out that we are losing some links from the site, but I think in this case they are all justifiable:

- User documentation on the Wiki is deprecated and will be removed - the new documentation site is the source of truth. Wiki is game data and developer information.
- Game data files have always been in the wiki and are linked in the user docs
- Areas of Focus has been mostly untouched for over two years, with a minor cleanup by Sev this year.
- Source code documentation is linked in the developer central - we could potentially put a link in the website menu outside the scope of the PR.

**Comment by cadihowley** [comment]
That would be my suggestion - having a link to developer central on the website if we remove the main link to the wiki. Everything else the user needs *should* be in the new docs, including references to game data files and other game related information on the wiki.

**Review by cadihowley — APPROVED** [review]

**Comment by Mataniko** [comment]
Pushed a new commit that adds links to the developer central and doxygen in the menu

**Pull request merged**
