### PR TITLE
WEB: Update introduction text

### PR DESCRIPTION
**Pull request by lotharsm**
This is my attempt to update the "intro" text on our website.

In my opinion, listing only a bunch of seemingly random games doesn't fit well anymore due to the large number of games we support nowadays.

Instead, I opted for another approach - only mentioning the most popular studios and games as well as teasing about all the obscure stuff and hidden gems we currently support with a more "generic", yet appealing approach.

As always, comments are very welcome.

### CODE REVIEW

**Comment by sev-** [comment]
reviewing these JSONs is basically impractical.

@Mataniko can we implement some kind of preprocessing that the newlines are allowed? Even preparing a news item became annoying these days: first I need to prepare the news item in human-readable format, and then carefully remove all the newlines. :(

**Comment by Mataniko** [comment]
I have something in the works for creating news articles, but for basic strings in the site, these JSON files are structured for weblate, where these changes can be done in a nice editor.

**Comment by lotharsm** [comment]
Any more comments regarding the content/change itself? ;)

**Comment by Mataniko** [comment]
I'd like the team to be empowered and have the freedom to make the site and its content better, please do not ask for approval to make minor changes like these.

**Comment by sev-** [comment]
The content is good, fine to merge.

**Comment by lotharsm** [comment]
Thanks, merging!

**Pull request merged**
