### PR TITLE
QFG4 - Hoyle5 announcement

### PR DESCRIPTION
**Pull request by bluegr**

### CODE REVIEW

**Comment by sluicebox** [comment]
Looks great, very exciting!

**Comment by bluegr** [comment]
The comments and feedback on this have peen positive on discord, IRC and github. Merging

**Comment by sluicebox** [comment]
Here are some screenshots that could be used

[screenshots.zip](https://github.com/scummvm/scummvm-web/files/3347830/screenshots.zip)

**Comment by bluegr** [comment]
Thanks for the screenshots @sluicebox! I've renamed yours and optimized them via optipng. I've also added shots for Hoyle Classic Games and Hoyle Solitaire (the other two are cut down versions of Hoyle Classic Games)
[screenshots_qfg4_hoyle5.zip](https://github.com/scummvm/scummvm-web/files/3365541/screenshots_qfg4_hoyle5.zip)

**Pull request merged**
