### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by tobiatesan**

### CODE REVIEW

**Comment by criezy** [comment]
Did you omit on purpose the locale and date format strings at the start of the lang.it.ini? Don't you want to translate dates to Italian?

It is also missing the some of the strings (for example all the strings from downloads.xml). It looks like you based your translation on an older version of the english lang.ini?

**Comment by tobiatesan** [comment]
I did. Thanks for catching it.

**Comment by sev-** [comment]
Any update?

**Comment by tobiatesan** [comment]
@criezy I've integrated the changes from cbda272, how does this look?

**Comment by sev-** [comment]
Merging, though the "new style paths" are present in menu.xml too. I'll take care of it.

**Pull request merged**
