### PR TITLE
IMAGES: Adding Sinister Six screenshots

### PR DESCRIPTION
**Pull request by SupSuper**
https://bugs.scummvm.org/ticket/13321

Marvel Comics Spider-Man: The Sinister Six (DOS/German)

### CODE REVIEW

**Comment by Thunderforge** [comment]
image

**Review by Thunderforge — CHANGES_REQUESTED** [review]
While J. Jonah Jameson may want lots of pictures of Spider-Man, [our ScummVM guidelines say](https://wiki.scummvm.org/index.php?title=Screenshots) we only need a few.

> For each game, we would like to have a small (say, between 2 and 5) number of screenshots which give users a good idea of what the game looks like to play. If the game is available in different languages or versions, it would also be nice to have a screenshot or two showing the differences of those versions.

Please reduce the count to no more than 10.

**Comment by neuromancer** [comment]
I can select 10 images (removing uninteresting and spoilery ones), but I don't have edit permission for @SupSuper's branch so I will only list the image filenames here.

**Comment by neuromancer** [comment]
These should be fine:

* sinistersix_dos_de_01.jpg
* sinistersix_dos_de_03.jpg
* sinistersix_dos_de_05.png
* sinistersix_dos_de_06.jpg
* sinistersix_dos_de_11.png
* sinistersix_dos_de_13.png
* sinistersix_dos_de_14.png
* sinistersix.png (logo)

**Comment by sev-** [comment]
Wiki says between 2 and 5, NOT 10. Screenshots are rotated on the front page and we want all games to be represented equally.

**Review by Thunderforge — APPROVED** [review]

**Comment by Thunderforge** [comment]
image

Thanks for submitting!

**Comment by Thunderforge** [comment]
Didn't realize until afterwards, but the filenames were missing the variant number (`1`). I fixed it in b86ccd8b86694b7a37ac2091d93bcffa3aecf213

**Pull request merged**
