### PR TITLE
WEB: Add themes to the website

### PR DESCRIPTION
**Pull request by Mataniko**
This PR enables the unused custom themes support from the website rewrite

Currently we have 2 additional themes: 
ResidualVM - 
image

Retro - 
image

### CODE REVIEW

**Comment by lotharsm** [comment]
One word: Awesome.

**Comment by sev-** [comment]
Great!

**Comment by Thunderforge** [comment]
Is the ResidualVM theme going to be used on the ResidualVM site? More generally, who will see these themes? Are they decided per user? Or do we decide if we want to flip all site visitors to the,?

**Comment by Mataniko** [comment]
No, the ResidualVM site is several years behind the ScummVM site, so the work is non-transferable. 

Users are able to change themes from the menu.

**Comment by bluegr** [comment]
> No, the ResidualVM site is several years behind the ScummVM site, so the work is non-transferable.
> 
> Users are able to change themes from the menu.

I would propose to only keep the CSS changes from these themes (i.e. only the colors), and use the latest ScummVM theme as a base for both themes

**Comment by Mataniko** [comment]
@bluegr Not sure I understand - can you please explain your comment?

**Pull request merged**
